baseURL = "http://pizzaandcode.com/"
languageCode = "en-us"
title = "Riccardo Lorenzon's blog"
publishdir = "/home/riccardo/workspace/riccardolorenzon.github.io/"
theme = "ezhil"

# Enable syntax highlighting.
pygmentsstyle = "vs"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
	# Blog subtitle which appears below blog title. Supports markdown.
	subtitle = "A blog of a coding and pizza eater specialist."
	# Number of posts to show in recent posts list (Optional). Defaults to 10.
	recentPostsCount = 10
	# Content types which are excluded from recent posts and archive page (Optional). Defaults to ["page"]
	excludedTypes = ["page"]
	# Content types which are excludes Disqus comments (Optional). Defaults to ["page"]
	disableDisqusTypes = ["page", "post"]
	# If social media links are enabled then enable this to fetch icons from CDN instead of hosted on your site.
	featherIconsCDN = true

# Main menu which appears below site header.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "About"
url = "/about"
weight = 2

# Social media links which shows up on site header.
# Uses feather icons for icons. You can [search icon names from here](https://feathericons.com/).
[[params.social]]
name = "Github"
icon = "github"
url = "//github.com/riccardolorenzon"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/ricky111986" 

# Enable tags.
[taxonomies]
   tag = "tags"
